[build]
  publish = "frontend/build"  # Yeh folder specify karta hai jahan aapki built site hai
  functions = "frontend/netlify/functions"  # Yeh path aapke serverless functions specify karta hai

[[redirects]]
  from = "/old-path"
  to = "/new-path"
  status = 301
