[build]
   
  functions = "frontend/netlify/functions"  # Yeh path aapke serverless functions specify karta hai
  base = "frontend"
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/old-path"
  to = "/new-path"
  status = 301
